import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import ingestion from '../workers/ingest/src/index';
import dashboard,{handle} from '../workers/dashboard/src/index';
import {data} from '../workers/dashboard/src/data';
import {User} from '../workers/dashboard/src/users';
import {Env,encodeCursor,failure} from '../shared/validation';
import {micropaySubmission} from '../shared/micropay-submission';
let mf:Miniflare;let env:Env;
const number='+972501234567',other='+972501234568',peer='+972509876543',token='a'.repeat(40),outToken='b'.repeat(40),message='שלום 👋\n& + "בדיקה" %20';
beforeAll(async()=>{mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-08-06',d1Databases:{DB:'sms-test'}});const bindings=await mf.getBindings();env={DB:bindings.DB as D1Database,INCOMING_TOKEN:token,OUTGOING_TOKEN:outToken};const dir=new URL('../migrations/',import.meta.url);for(const file of (await readdir(dir)).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile(new URL(file,dir),'utf8')).split(';').filter(s=>s.trim()))await env.DB.prepare(sql).run();});
afterAll(async()=>{await mf?.dispose();});
beforeEach(async()=>{await env.DB.batch([...['messages','user_numbers','sends','opt_outs','audit_log','settings','list_members','lists','contacts','users','system_numbers','imports'].map(t=>env.DB.prepare('DELETE FROM '+t)),env.DB.prepare('INSERT INTO system_numbers VALUES (?, ?, 1), (?, ?, 1)').bind(number,'Office',other,'Sales'),env.DB.prepare("INSERT INTO users (email,role,created_at) VALUES ('alice@example.com','user',1),('bob@example.com','user',1),('shared@example.com','user',1),('admin@example.com','admin',1)"),env.DB.prepare('INSERT INTO user_numbers (email,system_number) VALUES (?, ?), (?, ?), (?, ?), (?, ?)').bind('alice@example.com',number,'alice@example.com',other,'bob@example.com',other,'shared@example.com',number)]);});
const user=(email:string,role:'admin'|'user'='user'):User=>({email,name:'',role,can_bulk_send:0,daily_limit:null,density:null,columns:null,test_number:null,sessions_revoked_at:null,can_edit_contacts:1});
const ctx={waitUntil(){},passThroughOnException(){}} as unknown as ExecutionContext;
function send(body:Record<string,unknown>,out=false,secret=out?outToken:token){return ingestion.fetch(new Request('https://ingest.test'+(out?'/events/outgoing':'/hooks/incoming'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secret},body:JSON.stringify({event_id:'event-1',system_number:number,peer_number:peer,body:message,...body})}),env);}
async function read(email:string,query=''){const r=await data(new URL('https://dashboard.test/api/messages'+query),env,user(email));return r.json() as Promise<{messages:Record<string,unknown>[]}>;}
function callback(format='json',patch:Record<string,string>={},query='',auth=true){const payload={origsms:message,phone:'972509876543',dest:'0501234567',msgid:'00705d38b642d5423',cid:'12762',code:'שלום',sms:'not the full message',net:'97250',...patch};const headers:Record<string,string>=auth?{Authorization:'Bearer '+token}:{};if(format==='get')return new Request('https://ingest.test/hooks/micropay/incoming?'+new URLSearchParams(payload)+query,{headers});headers['Content-Type']=format==='json'?'application/json':'application/x-www-form-urlencoded';return new Request('https://ingest.test/hooks/micropay/incoming'+(query?'?'+query.replace(/^&/,''):''),{method:'POST',headers,body:format==='json'?JSON.stringify(payload):new URLSearchParams(payload).toString()});}
describe('normalized ingestion',()=>{
 it('preserves Unicode and stable-ID deduplication',async()=>{expect((await send({})).status).toBe(200);await send({});await send({event_id:'event-2'});const rows=await read('alice@example.com');expect(rows.messages).toHaveLength(2);expect(rows.messages[0].body).toBe(message);});
 it('keeps unidentified legitimate repeats',async()=>{await send({event_id:undefined});await send({event_id:undefined});expect((await read('alice@example.com')).messages).toHaveLength(2);});
 it('rejects invalid credentials, unknown and inactive numbers',async()=>{expect((await send({},false,'bad')).status).toBe(401);expect((await send({system_number:'+972501234569'})).status).toBe(403);expect((await send({},true,token)).status).toBe(401);expect((await ingestion.fetch(new Request('https://ingest.test/hooks/incoming?token='+token,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),env)).status).toBe(401);for(const INCOMING_TOKEN of [undefined,'short'])expect((await ingestion.fetch(new Request('https://ingest.test/hooks/incoming',{method:'POST',headers:{Authorization:'Bearer '+token}}),{...env,INCOMING_TOKEN})).status).toBe(503);await env.DB.prepare('UPDATE system_numbers SET active=0 WHERE number=?').bind(number).run();expect((await send({})).status).toBe(403);});
 it('rejects malformed/oversized messages and conflicting IDs',async()=>{expect((await send({body:''})).status).toBe(400);expect((await send({body:'x'.repeat(33000)})).status).toBe(413);await send({});expect((await send({body:'different'})).status).toBe(409);});
 it('updates older outbound messages without regressing finalized states',async()=>{await send({submission_status:'pending',occurred_at:'2020-01-01T00:00:00Z'},true);const before=await env.DB.prepare('SELECT updated_at,id FROM messages').first<{updated_at:number;id:number}>();await send({submission_status:'accepted'},true);await send({submission_status:'pending'},true);const rows=await read('alice@example.com','?since='+encodeCursor({t:before!.updated_at,id:before!.id}));expect(rows.messages).toHaveLength(1);expect(rows.messages[0].submission_status).toBe('accepted');expect(rows.messages[0].occurred_at).toBe(Date.parse('2020-01-01T00:00:00Z'));expect((await send({submission_status:'rejected'},true)).status).toBe(409);expect((await send({event_id:undefined,submission_status:'pending'},true)).status).toBe(400);});
});
describe('documented Micropay callbacks',()=>{
 it.each(['get','form','json'])('supports %s and returns a no-reply acknowledgement',async format=>{const r=await ingestion.fetch(callback(format),env);expect(r.status).toBe(200);expect(await r.text()).toBe(format==='json'?'{"reply":""}':'OK');expect(r.headers.get('Cache-Control')).toBe('no-store');const rows=await read('alice@example.com');expect(rows.messages[0]).toMatchObject({body:message,system_number:number,peer_number:peer,time_source:'receipt'});});
 it('deduplicates across transport formats by msgid',async()=>{for(const f of ['get','form','json'])await ingestion.fetch(callback(f),env);expect((await read('alice@example.com')).messages).toHaveLength(1);await ingestion.fetch(callback('json',{msgid:'new-id'}),env);expect((await read('alice@example.com')).messages).toHaveLength(2);});
 it('does not decode JSON text again or reconstruct origsms from sms',async()=>{await ingestion.fetch(callback('json',{origsms:'literal %2B + &',sms:'other'}),env);expect((await read('alice@example.com')).messages[0].body).toBe('literal %2B + &');expect((await ingestion.fetch(callback('json',{origsms:''}),env)).status).toBe(400);});
 it('requires stable IDs and rejects duplicates or mixed POST fields',async()=>{expect((await ingestion.fetch(callback('json',{msgid:''}),env)).status).toBe(400);expect((await ingestion.fetch(callback('get',{},'&msgid=duplicate'),env)).status).toBe(400);expect((await ingestion.fetch(callback('form',{},'&dest=0501234567'),env)).status).toBe(400);expect((await ingestion.fetch(callback('json',{body:'normalized'}),env)).status).toBe(400);});
 it('accepts the incoming token in the URL and rejects the outgoing token',async()=>{expect((await ingestion.fetch(callback('get',{},'',false),env)).status).toBe(401);for(const f of ['get','form','json'])expect((await ingestion.fetch(callback(f,{msgid:f},'&token='+token,false),env)).status).toBe(200);expect((await ingestion.fetch(callback('get',{},'&token='+outToken,false),env)).status).toBe(401);});
 it('requires dest to be a registered system number',async()=>{expect((await ingestion.fetch(callback('json',{dest:'0501234569'}),env)).status).toBe(403);const p={origsms:message,phone:'0509876543',msgid:'missing-dest'};expect((await ingestion.fetch(new Request('https://ingest.test/hooks/micropay/incoming',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(p)}),env)).status).toBe(400);expect((await ingestion.fetch(callback('json',{dest:'0501234568'}),env)).status).toBe(200);expect((await read('bob@example.com')).messages.map(m=>m.system_number)).toEqual([other]);});
 it('never returns success when storage fails',async()=>{const broken={...env,DB:{prepare(){throw new Error('storage unavailable');}} as unknown as D1Database};expect((await ingestion.fetch(callback(),broken)).status).toBe(503);expect((await ingestion.fetch(new Request('https://ingest.test/hooks/incoming',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({system_number:number,peer_number:peer,body:message})}),broken)).status).toBe(503);});
});
describe('authorization',()=>{
 beforeEach(async()=>{await send({});await env.DB.prepare('INSERT INTO messages(event_key,direction,system_number,peer_number,body,occurred_at,received_at,time_source,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind('other','in',other,peer,'sales',1,1,'receipt',1).run();});
 it('supports multiple assignments, shared numbers and empty users',async()=>{expect((await read('alice@example.com')).messages).toHaveLength(2);expect((await read('bob@example.com')).messages.map(m=>m.system_number)).toEqual([other]);expect((await read('shared@example.com')).messages.map(m=>m.system_number)).toEqual([number]);expect((await read('none@example.com')).messages).toHaveLength(0);});
 it('preserves isolation across number, peer, search and cursors',async()=>{await expect(read('bob@example.com','?system_number='+encodeURIComponent(number))).rejects.toMatchObject({status:403});expect((await read('bob@example.com','?peer_number='+encodeURIComponent(peer)+'&q=שלום')).messages).toHaveLength(0);for(const q of ['?cursor='+encodeCursor({t:Date.now(),id:999}),'?since='+encodeCursor({t:0,id:0})])expect((await read('bob@example.com',q)).messages.map(m=>m.system_number)).toEqual([other]);});
 it('does not trust email headers without a verified Access JWT',async()=>{const r=await dashboard.fetch(new Request('https://dashboard.test/api/messages',{headers:{'Cf-Access-Authenticated-User-Email':'alice@example.com'}}),{...env,ACCESS_ISSUER:'https://test.cloudflareaccess.com',ACCESS_AUD:'aud'},ctx);expect(r.status).toBe(401);expect(r.headers.get('Cache-Control')).toBe('no-store');});
});
describe('table queries',()=>{
 const third='+972509876544',day=(d:number)=>Date.parse('2026-01-0'+d+'T00:00:00Z');
 beforeEach(async()=>{await send({event_id:'a',peer_number:third,occurred_at:'2026-01-01T00:00:00Z'});await send({event_id:'b',occurred_at:'2026-01-02T00:00:00Z'});await send({event_id:'c',occurred_at:'2026-01-03T00:00:00Z',submission_status:'rejected'},true);await send({event_id:'d',peer_number:third,occurred_at:'2026-01-04T00:00:00Z',submission_status:'accepted'},true);});
 async function pages(query:string){const seen:number[]=[];let cursor='';for(let i=0;i<10;i++){const r=await (await data(new URL('https://dashboard.test/api/messages?limit=1&'+query+cursor),env,user('alice@example.com'))).json() as {messages:{occurred_at:number}[];next_cursor:string|null};seen.push(...r.messages.map(m=>m.occurred_at));if(!r.next_cursor)break;cursor='&cursor='+r.next_cursor;}return seen;}
 async function stats(email:string,query=''){return (await data(new URL('https://dashboard.test/api/stats'+query),env,user(email))).json();}
 it('sorts by every column and pages with keyset cursors',async()=>{expect(await pages('')).toEqual([day(4),day(3),day(2),day(1)]);expect(await pages('sort=time&order=asc')).toEqual([day(1),day(2),day(3),day(4)]);expect(await pages('sort=peer&order=asc')).toEqual([day(2),day(3),day(1),day(4)]);expect(await pages('sort=peer&order=desc')).toEqual([day(4),day(1),day(3),day(2)]);expect(await pages('sort=status&order=asc')).toEqual([day(1),day(2),day(4),day(3)]);expect(await pages('sort=direction&order=desc')).toEqual([day(4),day(3),day(2),day(1)]);expect(await pages('sort=number&order=asc')).toEqual([day(1),day(2),day(3),day(4)]);});
 it('filters by direction and status and summarizes the same filter',async()=>{expect((await read('alice@example.com','?direction=out')).messages.map(m=>m.occurred_at)).toEqual([day(4),day(3)]);expect((await read('alice@example.com','?status=rejected')).messages.map(m=>m.occurred_at)).toEqual([day(3)]);expect(await stats('alice@example.com')).toMatchObject({total:4,incoming:2,outgoing:2,peers:2});expect(await stats('alice@example.com','?direction=in&peer_number='+encodeURIComponent(third))).toMatchObject({total:1,incoming:1,outgoing:0,peers:1});expect(await stats('bob@example.com')).toEqual({total:0,incoming:0,outgoing:0,peers:0,max_id:0});expect(await (await handle(new Request('https://dashboard.test/api/me'),env,'alice@example.com')).json()).toMatchObject({email:'alice@example.com',role:'user',numbers:[{number,can_send:0},{number:other,can_send:0}]});});
 it('rejects unknown sorts, filters and mismatched cursors',async()=>{for(const q of ['?sort=body','?order=up','?direction=both','?status=delivered','?sort=peer&cursor='+encodeCursor({t:5,id:1}),'?cursor='+encodeCursor({t:'+972509876543',id:1})])await expect(read('alice@example.com',q)).rejects.toMatchObject({status:400});await expect(stats('bob@example.com','?system_number='+encodeURIComponent(number))).rejects.toMatchObject({status:403});});
});
const ORIGIN='https://dashboard.test';
async function api(email:string,path:string,body?:unknown,headers:Record<string,string>={Origin:ORIGIN}){try{return await handle(new Request(ORIGIN+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)}),env,email);}catch(e){return failure(e);}}
async function body(r:Response|Promise<Response>){return (await (await r).json()) as Record<string,unknown>;}
async function audits(){return (await env.DB.prepare('SELECT action FROM audit_log ORDER BY id').all<{action:string}>()).results.map(r=>r.action);}
describe('access and administration',()=>{
 it('admits only active users and blocks cross-site writes',async()=>{expect((await api('stranger@example.com','/api/me')).status).toBe(403);const page=await api('stranger@example.com','/');expect(page.status).toBe(403);expect(await page.text()).toContain('אין לך גישה');
  expect((await api('alice@example.com','/api/me/prefs',{density:'dense'},{})).status).toBe(403);expect((await api('alice@example.com','/api/me/prefs',{density:'dense'},{Origin:'https://evil.example'})).status).toBe(403);
  expect((await api('alice@example.com','/api/me/prefs',{density:'dense'})).status).toBe(200);expect(await (await api('alice@example.com','/api/me')).json()).toMatchObject({density:'dense'});
  await env.DB.prepare("UPDATE users SET active=0 WHERE email='alice@example.com'").run();expect((await api('alice@example.com','/api/me')).status).toBe(403);});
 it('keeps admin tools for admins, who see every active number',async()=>{expect((await api('alice@example.com','/api/admin/users')).status).toBe(403);expect((await api('alice@example.com','/admin')).status).toBe(302);expect((await api('admin@example.com','/admin')).status).toBe(200);
  await send({});await send({event_id:'sales',system_number:other});expect((await body(api('admin@example.com','/api/messages'))).messages).toHaveLength(2);
  expect(await (await api('admin@example.com','/api/me')).json()).toMatchObject({role:'admin',daily_limit:null,can_bulk_send:true,numbers:[{number,can_send:1},{number:other,can_send:1}]});});
 it('creates, updates and deletes users with per-number permissions',async()=>{const save=(body:Record<string,unknown>)=>api('admin@example.com','/api/admin/users/save',{create:false,name:'',role:'user',active:true,can_bulk_send:false,daily_limit:null,numbers:[],...body});
  expect((await save({create:true,email:' New@Example.com',name:'דנה',numbers:[{number,can_send:true}]})).status).toBe(200);expect(await (await api('new@example.com','/api/me')).json()).toMatchObject({name:'דנה',numbers:[{number,can_send:1}]});
  expect((await save({create:true,email:'new@example.com'})).status).toBe(409);expect((await save({email:'new@example.com',numbers:[{number:'+972501234599',can_send:false}]})).status).toBe(400);expect((await save({email:'missing@example.com'})).status).toBe(404);
  expect((await save({email:'new@example.com',daily_limit:50})).status).toBe(200);expect(await (await api('new@example.com','/api/me')).json()).toMatchObject({numbers:[],daily_limit:50});
  expect((await api('admin@example.com','/api/admin/users/delete',{email:'new@example.com'})).status).toBe(200);expect((await api('new@example.com','/api/me')).status).toBe(403);
  expect(await audits()).toEqual(['user.create','user.update','user.delete']);});
 it('never leaves the system without an active admin',async()=>{const base={create:false,name:'',active:true,can_bulk_send:false,daily_limit:null,numbers:[]};
  expect((await api('admin@example.com','/api/admin/users/save',{...base,email:'admin@example.com',role:'user'})).status).toBe(400);expect((await api('admin@example.com','/api/admin/users/delete',{email:'admin@example.com'})).status).toBe(400);
  expect((await api('admin@example.com','/api/admin/users/save',{...base,create:true,email:'boss@example.com',role:'admin'})).status).toBe(200);
  expect((await api('boss@example.com','/api/admin/users/save',{...base,email:'admin@example.com',role:'user'})).status).toBe(200);expect((await api('admin@example.com','/api/admin/users')).status).toBe(403);
  expect((await api('boss@example.com','/api/admin/users/save',{...base,email:'boss@example.com',role:'admin',active:false})).status).toBe(400);});
 it('validates and stores settings',async()=>{expect((await api('admin@example.com','/api/admin/settings',{refresh_seconds:1})).status).toBe(400);expect((await api('admin@example.com','/api/admin/settings',{allow_international:'yes'})).status).toBe(400);
  expect((await api('admin@example.com','/api/admin/settings',{org_name:' Acme ',max_recipients:2})).status).toBe(200);expect(await (await api('admin@example.com','/api/admin/settings')).json()).toMatchObject({org_name:'Acme',max_recipients:2,refresh_seconds:5});
  expect(await (await api('alice@example.com','/api/me')).json()).toMatchObject({settings:{org_name:'Acme',max_recipients:2}});expect(await audits()).toEqual(['settings.update']);});
 it('manages numbers and the opt-out list',async()=>{expect((await api('admin@example.com','/api/admin/numbers/save',{create:true,number:'050-123-4569',label:'New',active:true})).status).toBe(200);expect((await api('admin@example.com','/api/admin/numbers/save',{create:true,number:'+972501234569',label:'Again',active:true})).status).toBe(409);
  expect((await api('admin@example.com','/api/admin/numbers/save',{number:'+972501234569',label:'Old',active:false})).status).toBe(200);expect((await body(api('admin@example.com','/api/admin/numbers'))).numbers).toContainEqual({number:'+972501234569',label:'Old',active:0,users:0});
  expect(await (await api('admin@example.com','/api/admin/optouts/add',{numbers:['050-987-6543','nope']})).json()).toEqual({added:1,invalid:1});expect((await body(api('admin@example.com','/api/admin/optouts'))).optouts).toMatchObject([{number:peer,source:'manual',created_by:'admin@example.com'}]);
  expect((await api('admin@example.com','/api/admin/optouts/remove',{number:peer})).status).toBe(200);expect((await body(api('admin@example.com','/api/admin/optouts'))).optouts).toEqual([]);});
});
describe('sending',()=>{
 const third='+972509876544',fourth='+972509876545';
 function provider(reply:string|Error='OK 34556'){const calls:Record<string,string>[]=[];return {calls,fetcher:async(_url:string,init:RequestInit)=>{calls.push(JSON.parse(String(init.body)));if(reply instanceof Error)throw reply;return new Response(reply);}};}
 async function sendAs(email:string,body:Record<string,unknown>={},p=provider(),token:string|null='secret'){try{return await handle(new Request(ORIGIN+'/api/send',{method:'POST',headers:{'Content-Type':'application/json',Origin:ORIGIN},body:JSON.stringify({id:crypto.randomUUID(),system_number:number,recipients:[peer],body:'שלום',...body})}),{...env,MICROPAY_TOKEN:token??undefined},email,{fetcher:p.fetcher});}catch(e){return failure(e);}}
 beforeEach(async()=>{await env.DB.prepare("UPDATE user_numbers SET can_send=1 WHERE email='alice@example.com' AND system_number=?").bind(number).run();});
 it('sends from a permitted number once per send ID and logs each recipient',async()=>{const p=provider();const id=crypto.randomUUID();const r=await sendAs('alice@example.com',{id},p);
  expect(await r.json()).toMatchObject({id,status:'accepted',sent:1,task_id:'34556'});expect(p.calls).toEqual([expect.objectContaining({token:'secret',from:'0501234567',list:'0509876543',msg:'שלום'})]);
  expect((await read('alice@example.com','?direction=out')).messages).toMatchObject([{peer_number:peer,body:'שלום',submission_status:'accepted',sent_by:'alice@example.com'}]);
  expect(await (await sendAs('alice@example.com',{id},p)).json()).toMatchObject({duplicate:true,status:'accepted'});expect(p.calls).toHaveLength(1);expect((await sendAs('bob@example.com',{id})).status).toBe(409);expect(await audits()).toEqual(['send']);});
 it('enforces number, bulk, recipient and daily limits and skips opted-out numbers',async()=>{expect((await sendAs('bob@example.com',{system_number:other})).status).toBe(403);expect((await sendAs('alice@example.com',{system_number:other})).status).toBe(403);
  expect((await sendAs('alice@example.com',{recipients:[peer,third]})).status).toBe(403);
  await env.DB.batch([env.DB.prepare("UPDATE users SET can_bulk_send=1,daily_limit=3 WHERE email='alice@example.com'"),env.DB.prepare("INSERT INTO opt_outs VALUES (?,'manual',1,NULL)").bind(third),env.DB.prepare("INSERT INTO settings VALUES ('optout_text','\"להסרה השיבו הסר\"')")]);
  const p=provider();expect(await (await sendAs('alice@example.com',{recipients:[peer,third,'972509876545','nope','050-987-6543']},p)).json()).toMatchObject({status:'accepted',sent:2,skipped:{invalid:1,duplicates:1,opted_out:1}});
  expect(p.calls[0]).toMatchObject({list:'0509876543,0509876545',msg:'שלום\r\nלהסרה השיבו הסר'});expect((await read('alice@example.com','?direction=out')).messages.map(m=>m.peer_number).sort()).toEqual([peer,fourth]);
  const limited=await sendAs('alice@example.com',{recipients:[peer,fourth]});expect(limited.status).toBe(429);expect(await limited.json()).toMatchObject({error:expect.stringContaining('2 of 3')});
  await env.DB.prepare("INSERT INTO settings VALUES ('max_recipients','1')").run();expect((await sendAs('admin@example.com',{recipients:[peer,fourth]})).status).toBe(413);});
 it('records provider rejections and unknown results and never retries them',async()=>{expect(await (await sendAs('alice@example.com',{},provider('ERROR --> Description: invalid token'))).json()).toMatchObject({status:'rejected',error:expect.stringContaining('invalid token')});
  const p=provider(new Error('timeout'));expect(await (await sendAs('alice@example.com',{recipients:['0509876544']},p)).json()).toMatchObject({status:'unknown'});expect(p.calls).toHaveLength(1);
  expect((await read('alice@example.com','?direction=out')).messages.map(m=>m.submission_status).sort()).toEqual(['rejected','unknown']);expect((await sendAs('alice@example.com',{},provider(),null)).status).toBe(503);});
 it('adds customers who reply with an opt-out word to the opt-out list',async()=>{await send({event_id:'stop',body:' הסר! '});await send({event_id:'hello',peer_number:third,body:'הסר אותי מחר בבקשה'});
  expect((await env.DB.prepare('SELECT number,source FROM opt_outs').all()).results).toEqual([{number:peer,source:'keyword'}]);});
});
describe('columns, contacts, export, disconnect, test sends and lists',()=>{
 const third='+972509876544';
 it('saves visible columns and a test number per user and validates contact fields',async()=>{expect((await api('alice@example.com','/api/me/prefs',{columns:['time','c:name','body']})).status).toBe(200);expect((await api('alice@example.com','/api/me/prefs',{columns:['time;drop']})).status).toBe(400);
  expect((await api('alice@example.com','/api/me/prefs',{test_number:'050-987-6543'})).status).toBe(200);
  expect(await body(api('alice@example.com','/api/me'))).toMatchObject({columns:['time','c:name','body'],test_number:peer,contact_fields:[{id:'name'},{id:'id_number'}]});
  expect((await api('admin@example.com','/api/admin/settings',{contact_fields:[{id:'Bad Id',label:'x'}]})).status).toBe(400);expect((await api('admin@example.com','/api/admin/settings',{contact_fields:[{id:'city',label:'עיר'}]})).status).toBe(200);
  expect(await body(api('alice@example.com','/api/me'))).toMatchObject({contact_fields:[{id:'city',label:'עיר'}]});});
 it('filters by several values per column and by contained text',async()=>{await send({event_id:'a',body:'שלום עולם'});await send({event_id:'b',peer_number:third,body:'מחיר?'});await send({event_id:'c',system_number:other,body:'sales'});await send({event_id:'d',submission_status:'rejected',body:'reply'},true);await send({event_id:'e',submission_status:'accepted',body:'ok',peer_number:third},true);
  const bodies=async(q:string)=>((await body(api('admin@example.com','/api/messages'+q))).messages as {body:string}[]).map(m=>m.body).sort();
  expect(await bodies('?status=rejected,accepted')).toEqual(['ok','reply']);expect(await bodies('?system_number='+encodeURIComponent(number+','+other)+'&direction=in')).toEqual(['sales','מחיר?','שלום עולם'].sort());
  expect(await bodies('?peer_q=050-987-6544')).toEqual(['ok','מחיר?'].sort());expect(await bodies('?body_q=עולם')).toEqual(['שלום עולם']);
  expect((await api('alice@example.com','/api/messages?system_number='+encodeURIComponent(number+',+972501234599'))).status).toBe(403);});
 it('joins contact data for display, search, filters, sorting and logs exports',async()=>{await api('admin@example.com','/api/admin/contacts/save',{number:'050-987-6543',data:{name:'דנה',id_number:'123',ignored:'x'}});await api('admin@example.com','/api/admin/contacts/save',{number:third,data:{name:'אבי'}});
  await send({event_id:'a'});await send({event_id:'b',peer_number:third});await send({event_id:'c',peer_number:'+972509876545'});
  expect(((await body(api('alice@example.com','/api/messages?sort=c:name&order=asc'))).messages as {contact:unknown}[]).map(m=>m.contact)).toEqual([null,{name:'אבי'},{name:'דנה',id_number:'123'}]);
  const p1=await body(api('alice@example.com','/api/messages?sort=c:name&order=desc&limit=1'));expect(p1.messages).toMatchObject([{contact:{name:'דנה'}}]);expect(await body(api('alice@example.com','/api/messages?sort=c:name&order=desc&limit=1&cursor='+p1.next_cursor))).toMatchObject({messages:[{contact:{name:'אבי'}}]});
  expect((await body(api('alice@example.com','/api/messages?q=דנה'))).messages).toHaveLength(1);expect((await body(api('alice@example.com','/api/messages?cf_name=אב'))).messages).toHaveLength(1);
  expect((await api('alice@example.com','/api/messages?sort=c:nope')).status).toBe(400);expect((await api('alice@example.com','/api/messages?limit=500')).status).toBe(400);
  const first=await body(api('alice@example.com','/api/messages?limit=2&export=1&columns=time,c:name&format=csv'));expect(first.messages).toHaveLength(2);
  expect((await api('alice@example.com','/api/messages?limit=2&export=1&cursor='+first.next_cursor)).status).toBe(200);expect(await audits()).toEqual(['contact.save','contact.save','export']);});
 it('imports contacts, merging or skipping existing ones',async()=>{await api('admin@example.com','/api/admin/contacts/save',{number:peer,data:{name:'דנה',id_number:'1'}});
  expect(await body(api('admin@example.com','/api/admin/contacts/import',{mode:'skip',rows:[{number:'0509876543',data:{name:'X'}},{number:'972509876544',data:{name:'אבי'}},{number:'bad',data:{}}]}))).toEqual({imported:1,invalid:1});
  expect(await body(api('admin@example.com','/api/admin/contacts/import',{mode:'update',rows:[{number:peer,data:{id_number:'2'}}]}))).toEqual({imported:1,invalid:0});
  expect((await body(api('admin@example.com','/api/admin/contacts'))).contacts).toEqual(expect.arrayContaining([expect.objectContaining({number:peer,data:{name:'דנה',id_number:'2'}}),expect.objectContaining({number:third,data:{name:'אבי'}})]));
  expect((await api('alice@example.com','/api/admin/contacts')).status).toBe(403);expect((await api('admin@example.com','/api/admin/contacts/delete',{number:peer})).status).toBe(200);expect((await body(api('admin@example.com','/api/admin/contacts'))).total).toBe(1);});
 it('ends a user session on disconnect and can also disable them',async()=>{const old={email:'alice@example.com',iat:Math.floor(Date.now()/1000)-60};expect((await handle(new Request(ORIGIN+'/api/me'),env,old)).status).toBe(200);
  expect((await api('admin@example.com','/api/admin/users/disconnect',{email:'admin@example.com'})).status).toBe(400);expect((await api('admin@example.com','/api/admin/users/disconnect',{email:'alice@example.com'})).status).toBe(200);
  await expect(handle(new Request(ORIGIN+'/api/me'),env,old)).rejects.toMatchObject({status:401});expect((await handle(new Request(ORIGIN+'/'),env,old)).status).toBe(401);
  expect((await handle(new Request(ORIGIN+'/api/me'),env,{email:'alice@example.com',iat:Math.floor(Date.now()/1000)+1})).status).toBe(200);
  expect((await api('admin@example.com','/api/admin/users/disconnect',{email:'alice@example.com',disable:true})).status).toBe(200);expect((await api('alice@example.com','/api/me')).status).toBe(403);expect(await audits()).toEqual(['user.disconnect','user.disconnect']);});
 it('sends a test to one number with the opt-out text a multi-recipient send would carry',async()=>{await env.DB.batch([env.DB.prepare("UPDATE user_numbers SET can_send=1 WHERE email='alice@example.com' AND system_number=?").bind(number),env.DB.prepare("INSERT INTO settings VALUES ('optout_text','\"להסרה השיבו הסר\"')")]);
  const calls:string[]=[];const fetcher=async(_u:string,init:RequestInit)=>{calls.push(JSON.parse(String(init.body)).msg);return new Response('OK 7');};
  const test=(b:Record<string,unknown>)=>handle(new Request(ORIGIN+'/api/send',{method:'POST',headers:{'Content-Type':'application/json',Origin:ORIGIN},body:JSON.stringify({id:crypto.randomUUID(),test:true,system_number:number,body:'שלום',...b})}),{...env,MICROPAY_TOKEN:'t'},'alice@example.com',{fetcher}).catch(failure);
  expect((await test({recipients:[peer,third]})).status).toBe(400);expect(await body(test({recipients:[peer],bulk_preview:true}))).toMatchObject({status:'accepted',sent:1});expect(await body(test({recipients:[peer]}))).toMatchObject({status:'accepted'});
  expect(calls).toEqual(['שלום\r\nלהסרה השיבו הסר','שלום']);expect((await read('alice@example.com','?direction=out')).messages.map(m=>m.is_test)).toEqual([1,1]);});
 it('keeps lists private unless an admin shares them',async()=>{const save=(email:string,b:Record<string,unknown>)=>api(email,'/api/lists/save',{name:'VIP',numbers:[],...b});
  const mine=await body(save('alice@example.com',{numbers:['050-987-6543','0509876543','bad']}));expect(mine).toMatchObject({size:1,invalid:1});expect((await save('alice@example.com',{shared:true})).status).toBe(403);
  const shared=await body(save('admin@example.com',{name:'כולם',shared:true,numbers:[third]}));
  expect(((await body(api('bob@example.com','/api/lists'))).lists as {name:string;editable:boolean}[]).map(l=>[l.name,l.editable])).toEqual([['כולם',false]]);
  expect((await api('bob@example.com','/api/lists/members?id='+mine.id)).status).toBe(404);expect((await body(api('bob@example.com','/api/lists/members?id='+shared.id))).numbers).toEqual([third]);expect((await save('bob@example.com',{id:shared.id})).status).toBe(403);
  expect((await save('alice@example.com',{id:mine.id,name:'VIP 2',numbers:[peer,third]})).status).toBe(200);expect(((await body(api('alice@example.com','/api/lists'))).lists as {name:string;size:number}[]).map(l=>[l.name,l.size])).toEqual([['כולם',1],['VIP 2',2]]);
  expect((await api('bob@example.com','/api/lists/delete',{id:mine.id})).status).toBe(403);expect((await api('alice@example.com','/api/lists/delete',{id:mine.id})).status).toBe(200);});
});
describe('profile sign-out and contact editing by users',()=>{
 const third='+972509876544';
 it('logs a sign-out and requires a same-origin request',async()=>{expect((await api('alice@example.com','/api/me/logout',{},{Origin:'https://evil.test'})).status).toBe(403);expect((await api('alice@example.com','/api/me/logout',{})).status).toBe(200);expect(await audits()).toEqual(['user.logout']);});
 it('lets users edit only changed fields of customers in their messages',async()=>{await send({});await env.DB.prepare('INSERT INTO messages(event_key,direction,system_number,peer_number,body,occurred_at,received_at,time_source,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind('third','in',other,third,'x',1,1,'receipt',1).run();
  expect(await body(api('alice@example.com','/api/me'))).toMatchObject({can_edit_contacts:true});
  expect(await body(api('alice@example.com','/api/contacts/save',{number:'050-987-6543',data:{name:' דנה '}}))).toEqual({ok:true,number:peer,data:{name:'דנה'}});
  expect(await body(api('shared@example.com','/api/contacts/save',{number:peer,data:{id_number:'123'}}))).toMatchObject({data:{name:'דנה',id_number:'123'}});
  expect(await body(api('alice@example.com','/api/contacts/save',{number:peer,data:{name:''}}))).toMatchObject({data:{id_number:'123'}});
  expect((await api('shared@example.com','/api/contacts/save',{number:third,data:{name:'x'}})).status).toBe(403);expect((await api('bob@example.com','/api/contacts/save',{number:third,data:{name:'אבי'}})).status).toBe(200);
  expect((await api('alice@example.com','/api/contacts/save',{number:peer,data:{unknown:'x'}})).status).toBe(400);expect((await api('alice@example.com','/api/contacts/save',{number:peer,data:{}})).status).toBe(400);expect((await api('alice@example.com','/api/contacts/save',{number:peer,data:{name:'x'.repeat(201)}})).status).toBe(400);
  expect(await body(api('admin@example.com','/api/contacts/save',{number:'0521112222',data:{name:'חדש'}}))).toMatchObject({data:{name:'חדש'}});
  expect(await body(api('bob@example.com','/api/contacts/save',{number:third,data:{name:''}}))).toMatchObject({data:null});expect(await env.DB.prepare('SELECT 1 FROM contacts WHERE number=?').bind(third).first()).toBeNull();
  expect((await audits()).filter(a=>a==='contact.save')).toHaveLength(6);});
 it('lets admins turn contact editing off per user',async()=>{await send({});const save=(flag?:boolean)=>api('admin@example.com','/api/admin/users/save',{email:'alice@example.com',role:'user',active:true,can_bulk_send:false,daily_limit:null,numbers:[{number,can_send:false}],...(flag===undefined?{}:{can_edit_contacts:flag})});
  expect((await save(false)).status).toBe(200);expect(await body(api('alice@example.com','/api/me'))).toMatchObject({can_edit_contacts:false});expect((await api('alice@example.com','/api/contacts/save',{number:peer,data:{name:'x'}})).status).toBe(403);
  expect(((await body(api('admin@example.com','/api/admin/users'))).users as {email:string;can_edit_contacts:number}[]).find(u=>u.email==='alice@example.com')?.can_edit_contacts).toBe(0);
  expect((await save()).status).toBe(200);expect((await api('alice@example.com','/api/contacts/save',{number:peer,data:{name:'x'}})).status).toBe(200);});
});
describe('message import',()=>{
 const t0=Date.UTC(2026,9,7,9,0);
 const row=(r:Record<string,unknown>)=>({row:2,direction:'in',system_number:number,peer_number:'0509876543',body:'שלום',occurred_at:t0,...r});
 async function start(total=10){return (await body(api('admin@example.com','/api/admin/imports/start',{file:'history.xlsx',total}))).id as number;}
 const rowsOf=(id:number,rows:unknown[])=>api('admin@example.com','/api/admin/imports/rows',{id,rows});
 it('stores rows, skips duplicates by message ID, within 10 minutes and on re-upload, and adds opt-outs',async()=>{
  expect((await ingestion.fetch(callback('json',{msgid:'mp-1'}),env)).status).toBe(200);
  const id=await start();
  const rows=[row({msgid:'mp-1',body:message}),row({row:3,body:'כן'}),row({row:4,body:'כן',n:1}),row({row:5,direction:'out',body:'תודה',status:'rejected',occurred_at:t0+60000}),row({row:6,body:'הסר',peer_number:'0521112222'}),row({row:7,body:'בלי זמן',occurred_at:null}),row({row:8,system_number:'0501234569'}),row({row:9,peer_number:'abc'})];
  const first=await body(rowsOf(id,rows));expect(first).toMatchObject({added:5,duplicates:1});expect(first.invalid).toEqual([{row:8,reason:'מספר המערכת אינו רשום או אינו פעיל'},{row:9,reason:'מספר הלקוח אינו תקין'}]);
  expect(await body(rowsOf(id,rows))).toMatchObject({added:0,duplicates:6});
  expect(await body(rowsOf(id,[row({row:10,body:'כן',occurred_at:t0+9*60000}),row({row:11,body:'כן',occurred_at:t0+11*60000})]))).toMatchObject({added:1,duplicates:1});
  const stored=await env.DB.prepare('SELECT direction,body,occurred_at,time_source,submission_status,import_id FROM messages WHERE import_id=? ORDER BY id').bind(id).all<Record<string,unknown>>();
  expect(stored.results.map(r=>r.body)).toEqual(['כן','כן','תודה','הסר','בלי זמן','כן']);expect(stored.results[2]).toMatchObject({direction:'out',submission_status:'rejected',time_source:'provider'});expect(stored.results[4]).toMatchObject({time_source:'receipt'});
  expect(await env.DB.prepare("SELECT source FROM opt_outs WHERE number='+972521112222'").first()).toEqual({source:'keyword'});
  expect((await body(api('admin@example.com','/api/admin/imports'))).imports).toMatchObject([{id,file:'history.xlsx',added:6,duplicates:8,invalid:4}]);
  expect(((await read('alice@example.com','?limit=100')).messages.filter(m=>m.import_id===id))).toHaveLength(6);});
 it('undoes exactly the messages an import added',async()=>{expect((await send({})).status).toBe(200);const id=await start();await rowsOf(id,[row({body:'a'}),row({body:'b'})]);
  expect(await body(api('admin@example.com','/api/admin/imports/undo',{id}))).toEqual({removed:2});expect((await read('alice@example.com')).messages).toHaveLength(1);
  expect((await api('admin@example.com','/api/admin/imports/undo',{id})).status).toBe(409);expect((await rowsOf(id,[row({body:'c'})])).status).toBe(409);
  expect(await audits()).toEqual(['messages.import','messages.import.undo']);});
 it('is for admins only and validates batches',async()=>{expect((await api('alice@example.com','/api/admin/imports/start',{file:'x',total:1})).status).toBe(403);expect((await api('alice@example.com','/api/admin/imports')).status).toBe(403);
  const id=await start();expect((await rowsOf(id,[])).status).toBe(400);expect((await rowsOf(id,Array.from({length:501},()=>row({})))).status).toBe(400);expect((await rowsOf(999,[row({})])).status).toBe(404);
  expect(await body(rowsOf(id,[row({direction:'sideways'}),row({occurred_at:'yesterday'}),row({body:' '})]))).toMatchObject({added:0,invalid:[{reason:'כיוון לא תקין'},{reason:'תאריך לא תקין'},{reason:'ההודעה ריקה'}]});});
});
describe('D1 rows read',()=>{
 // Records rows_read per query, since D1 bills rows read rather than rows returned.
 function metered(){const log:{sql:string;read:number}[]=[];const wrap=(st:D1PreparedStatement,sql:string):D1PreparedStatement=>new Proxy(st,{get(t,k){if(k==='bind')return(...a:unknown[])=>wrap(t.bind(...a),sql);if(k==='all')return async()=>{const r=await t.all();log.push({sql,read:r.meta.rows_read});return r;};const v=Reflect.get(t,k);return typeof v==='function'?v.bind(t):v;}});
  const db=new Proxy(env.DB,{get(t,k){if(k==='prepare')return(sql:string)=>wrap(t.prepare(sql),sql);const v=Reflect.get(t,k);return typeof v==='function'?v.bind(t):v;}});return {env:{...env,DB:db},log};}
 beforeEach(async()=>{await env.DB.prepare("WITH RECURSIVE n(i) AS (SELECT 1 UNION ALL SELECT i+1 FROM n WHERE i<500) INSERT INTO messages(event_key,direction,system_number,peer_number,body,occurred_at,received_at,time_source,updated_at) SELECT 'bulk'||i,'in',?,'+9725099'||printf('%05d',i%50),'x',i*1000,i*1000,'receipt',i*1000 FROM n").bind(number).run();});
 it('reads only new rows when polling and one page when opening the table',async()=>{for(const who of [user('alice@example.com'),user('admin@example.com','admin')]){
  const m=metered();const first=await (await data(new URL('https://dashboard.test/api/messages?limit=100'),m.env,who)).json() as {sync_cursor:string};
  expect(m.log.at(-1)!.read).toBeLessThan(150);
  await data(new URL('https://dashboard.test/api/messages?limit=100&since='+encodeURIComponent(first.sync_cursor)),m.env,who);expect(m.log.at(-1)!.read).toBeLessThan(10);
  await data(new URL('https://dashboard.test/api/messages?limit=100&since='+encodeURIComponent(encodeCursor({t:400000,id:0}))),m.env,who);expect(m.log.at(-1)!.read).toBeLessThan(120);}});
});
describe('Micropay submission responses',()=>{
 it('recognizes plain and JSON queue acceptance, including validate variants',()=>{for(const raw of ['OK 34556','OK 250 34556','OK VALID 34556',{status:1,message:'OK',data:{taskId:'34556'}}])expect(micropaySubmission(raw)).toEqual({submission_status:'accepted',task_id:'34556'});});
 it('does not treat status=1 alone, timeouts or unknown responses as acceptance',()=>{expect(micropaySubmission({status:1,message:'NOT_ENOUGH_CREDIT'})).toEqual({submission_status:'unknown'});expect(micropaySubmission('timeout')).toEqual({submission_status:'unknown'});expect(micropaySubmission({status:0,message:'ERROR'})).toEqual({submission_status:'rejected'});expect(micropaySubmission('ERROR --> Description: invalid token')).toEqual({submission_status:'rejected'});});
});
