import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import {Miniflare} from 'miniflare';
import {readFile} from 'node:fs/promises';
import ingestion from '../workers/ingest/src/index';
import dashboard from '../workers/dashboard/src/index';
import {data} from '../workers/dashboard/src/data';
import {Env,encodeCursor} from '../shared/validation';
import {micropaySubmission} from '../shared/micropay-submission';
let mf:Miniflare;let env:Env;
const number='+972501234567',other='+972501234568',peer='+972509876543',token='a'.repeat(40),outToken='b'.repeat(40),message='שלום 👋\n& + "בדיקה" %20';
beforeAll(async()=>{mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-08-06',d1Databases:{DB:'sms-test'}});const bindings=await mf.getBindings();env={DB:bindings.DB as D1Database,INGEST_CREDENTIALS_JSON:JSON.stringify([{token,source:'incoming',direction:'in',numbers:[number]},{token:outToken,source:'workflow',direction:'out',numbers:[number]}])};const schema=await readFile(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8');for(const sql of schema.split(';').filter(s=>s.trim()))await env.DB.prepare(sql).run();});
afterAll(async()=>{await mf?.dispose();});
beforeEach(async()=>{await env.DB.batch([env.DB.prepare('DELETE FROM messages'),env.DB.prepare('DELETE FROM user_numbers'),env.DB.prepare('DELETE FROM system_numbers'),env.DB.prepare('INSERT INTO system_numbers VALUES (?, ?, 1), (?, ?, 1)').bind(number,'Office',other,'Sales'),env.DB.prepare('INSERT INTO user_numbers VALUES (?, ?), (?, ?), (?, ?), (?, ?)').bind('alice@example.com',number,'alice@example.com',other,'bob@example.com',other,'shared@example.com',number)]);});
function send(body:Record<string,unknown>,out=false,secret=out?outToken:token){return ingestion.fetch(new Request('https://ingest.test'+(out?'/events/outgoing':'/hooks/incoming'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secret},body:JSON.stringify({event_id:'event-1',system_number:number,peer_number:peer,body:message,...body})}),env);}
async function read(email:string,query=''){const r=await data(new URL('https://dashboard.test/api/messages'+query),env,email);return r.json() as Promise<{messages:Record<string,unknown>[]}>;}
function callback(format='json',patch:Record<string,string>={},query='',auth=true){const payload={origsms:message,phone:'972509876543',dest:'0501234567',msgid:'00705d38b642d5423',cid:'12762',code:'שלום',sms:'not the full message',net:'97250',...patch};const headers:Record<string,string>=auth?{Authorization:'Bearer '+token}:{};if(format==='get')return new Request('https://ingest.test/hooks/micropay/incoming?'+new URLSearchParams(payload)+query,{headers});headers['Content-Type']=format==='json'?'application/json':'application/x-www-form-urlencoded';return new Request('https://ingest.test/hooks/micropay/incoming'+(query?'?'+query.replace(/^&/,''):''),{method:'POST',headers,body:format==='json'?JSON.stringify(payload):new URLSearchParams(payload).toString()});}
describe('normalized ingestion',()=>{
 it('preserves Unicode and stable-ID deduplication',async()=>{expect((await send({})).status).toBe(200);await send({});await send({event_id:'event-2'});const rows=await read('alice@example.com');expect(rows.messages).toHaveLength(2);expect(rows.messages[0].body).toBe(message);});
 it('keeps unidentified legitimate repeats',async()=>{await send({event_id:undefined});await send({event_id:undefined});expect((await read('alice@example.com')).messages).toHaveLength(2);});
 it('rejects invalid credentials, out-of-scope and inactive numbers',async()=>{expect((await send({},false,'bad')).status).toBe(401);expect((await send({system_number:other})).status).toBe(403);expect((await send({},true,token)).status).toBe(401);await env.DB.prepare('UPDATE system_numbers SET active=0 WHERE number=?').bind(number).run();expect((await send({})).status).toBe(403);});
 it('rejects malformed/oversized messages and conflicting IDs',async()=>{expect((await send({body:''})).status).toBe(400);expect((await send({body:'x'.repeat(33000)})).status).toBe(413);await send({});expect((await send({body:'different'})).status).toBe(409);});
 it('updates older outbound messages without regressing finalized states',async()=>{await send({submission_status:'pending',occurred_at:'2020-01-01T00:00:00Z'},true);const before=await env.DB.prepare('SELECT updated_at,id FROM messages').first<{updated_at:number;id:number}>();await send({submission_status:'accepted'},true);await send({submission_status:'pending'},true);const rows=await read('alice@example.com','?since='+encodeCursor({t:before!.updated_at,id:before!.id}));expect(rows.messages).toHaveLength(1);expect(rows.messages[0].submission_status).toBe('accepted');expect(rows.messages[0].occurred_at).toBe(Date.parse('2020-01-01T00:00:00Z'));expect((await send({submission_status:'rejected'},true)).status).toBe(409);expect((await send({event_id:undefined,submission_status:'pending'},true)).status).toBe(400);});
});
describe('documented Micropay callbacks',()=>{
 it.each(['get','form','json'])('supports %s and returns a no-reply acknowledgement',async format=>{const r=await ingestion.fetch(callback(format),env);expect(r.status).toBe(200);expect(await r.text()).toBe(format==='json'?'{"reply":""}':'OK');expect(r.headers.get('Cache-Control')).toBe('no-store');const rows=await read('alice@example.com');expect(rows.messages[0]).toMatchObject({body:message,system_number:number,peer_number:peer,time_source:'receipt'});});
 it('deduplicates across transport formats by msgid',async()=>{for(const f of ['get','form','json'])await ingestion.fetch(callback(f),env);expect((await read('alice@example.com')).messages).toHaveLength(1);await ingestion.fetch(callback('json',{msgid:'new-id'}),env);expect((await read('alice@example.com')).messages).toHaveLength(2);});
 it('does not decode JSON text again or reconstruct origsms from sms',async()=>{await ingestion.fetch(callback('json',{origsms:'literal %2B + &',sms:'other'}),env);expect((await read('alice@example.com')).messages[0].body).toBe('literal %2B + &');expect((await ingestion.fetch(callback('json',{origsms:''}),env)).status).toBe(400);});
 it('requires stable IDs and rejects duplicates or mixed POST fields',async()=>{expect((await ingestion.fetch(callback('json',{msgid:''}),env)).status).toBe(400);expect((await ingestion.fetch(callback('get',{},'&msgid=duplicate'),env)).status).toBe(400);expect((await ingestion.fetch(callback('form',{},'&dest=0501234567'),env)).status).toBe(400);expect((await ingestion.fetch(callback('json',{body:'normalized'}),env)).status).toBe(400);});
 it('keeps URL credentials opt-in and rejects outgoing credentials',async()=>{const request=()=>callback('get',{},'&hook_token='+token,false);expect((await ingestion.fetch(request(),env)).status).toBe(401);expect((await ingestion.fetch(request(),{...env,MICROPAY_ALLOW_URL_TOKEN:'true'})).status).toBe(200);expect((await ingestion.fetch(callback('get',{},'&hook_token='+outToken,false),{...env,MICROPAY_ALLOW_URL_TOKEN:'true'})).status).toBe(401);});
 it('enforces number scope and derives a missing dest only from a single-number credential',async()=>{expect((await ingestion.fetch(callback('json',{dest:'0501234568'}),env)).status).toBe(403);const p={origsms:message,phone:'0509876543',msgid:'missing-dest'};const r=await ingestion.fetch(new Request('https://ingest.test/hooks/micropay/incoming',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(p)}),env);expect(r.status).toBe(200);expect((await read('alice@example.com')).messages[0].system_number).toBe(number);});
 it('never returns success when storage fails',async()=>{const broken={...env,DB:{prepare(){throw new Error('storage unavailable');}} as unknown as D1Database};expect((await ingestion.fetch(callback(),broken)).status).toBe(503);expect((await ingestion.fetch(new Request('https://ingest.test/hooks/incoming',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({system_number:number,peer_number:peer,body:message})}),broken)).status).toBe(503);});
});
describe('authorization',()=>{
 beforeEach(async()=>{await send({});await env.DB.prepare('INSERT INTO messages(event_key,direction,system_number,peer_number,body,occurred_at,received_at,time_source,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind('other','in',other,peer,'sales',1,1,'receipt',1).run();});
 it('supports multiple assignments, shared numbers and empty users',async()=>{expect((await read('alice@example.com')).messages).toHaveLength(2);expect((await read('bob@example.com')).messages.map(m=>m.system_number)).toEqual([other]);expect((await read('shared@example.com')).messages.map(m=>m.system_number)).toEqual([number]);expect((await read('none@example.com')).messages).toHaveLength(0);});
 it('preserves isolation across number, peer, search and cursors',async()=>{await expect(read('bob@example.com','?system_number='+encodeURIComponent(number))).rejects.toMatchObject({status:403});expect((await read('bob@example.com','?peer_number='+encodeURIComponent(peer)+'&q=שלום')).messages).toHaveLength(0);for(const q of ['?cursor='+encodeCursor({t:Date.now(),id:999}),'?since='+encodeCursor({t:0,id:0})])expect((await read('bob@example.com',q)).messages.map(m=>m.system_number)).toEqual([other]);});
 it('does not trust email headers without a verified Access JWT',async()=>{const r=await dashboard.fetch(new Request('https://dashboard.test/api/messages',{headers:{'Cf-Access-Authenticated-User-Email':'alice@example.com'}}),{...env,ACCESS_ISSUER:'https://test.cloudflareaccess.com',ACCESS_AUD:'aud'});expect(r.status).toBe(401);expect(r.headers.get('Cache-Control')).toBe('no-store');});
});
describe('Micropay submission responses',()=>{
 it('recognizes plain and JSON queue acceptance, including validate variants',()=>{for(const raw of ['OK 34556','OK 250 34556','OK VALID 34556',{status:1,message:'OK',data:{taskId:'34556'}}])expect(micropaySubmission(raw)).toEqual({submission_status:'accepted',task_id:'34556'});});
 it('does not treat status=1 alone, timeouts or unknown responses as acceptance',()=>{expect(micropaySubmission({status:1,message:'NOT_ENOUGH_CREDIT'})).toEqual({submission_status:'unknown'});expect(micropaySubmission('timeout')).toEqual({submission_status:'unknown'});expect(micropaySubmission({status:0,message:'ERROR'})).toEqual({submission_status:'rejected'});expect(micropaySubmission('ERROR --> Description: invalid token')).toEqual({submission_status:'rejected'});});
});
