export function page(nonce:string):string {return `<!doctype html>
<html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>שיחות SMS</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;font:16px system-ui,sans-serif;background:#f5f7fa;color:#172033}header{background:#172033;color:white;padding:18px}h1{margin:0;font-size:24px}.note{font-size:13px;opacity:.8}.filters{display:flex;gap:10px;flex-wrap:wrap;padding:16px;background:white}label{display:grid;gap:4px;font-size:13px}input,select,button{font:inherit;padding:9px;border:1px solid #ccd2dc;border-radius:7px}button{cursor:pointer;background:#fff}button:disabled{opacity:.5;cursor:wait}main{display:grid;grid-template-columns:300px 1fr;gap:16px;padding:16px;max-width:1300px;margin:auto}aside,.thread{background:white;border-radius:10px;padding:12px}#conversations{display:grid;gap:8px;max-height:70vh;overflow:auto}#conversations button{text-align:right}#conversations button[aria-pressed=true]{border:2px solid #335db8;background:#edf3ff}#messages{display:flex;flex-direction:column;gap:10px;min-height:160px}.bubble{padding:12px;border-radius:10px;background:#f0f3f9;max-width:90%;align-self:flex-start}.bubble.out{background:#e4f3e9;align-self:flex-end}.body{white-space:pre-wrap;overflow-wrap:anywhere;unicode-bidi:plaintext}.meta{font-size:12px;color:#536078;margin-top:8px}.phone{direction:ltr;unicode-bidi:embed}#status{padding:8px 16px;min-height:35px;color:#8b2828}footer{padding:16px;text-align:center;color:#647084;font-size:12px}@media(max-width:700px){main{grid-template-columns:1fr}#conversations{max-height:200px}.bubble{max-width:100%}.filters>*{flex:1 1 140px}}</style></head>
<body><header><h1>שיחות SMS</h1><p class="note">צפייה בלבד · מצב הגשה אינו אישור מסירה</p></header>
<form class="filters" id="filters"><label>מספר מערכת<select id="number"><option value="">כל המספרים</option></select></label><label>חיפוש<input id="query" maxlength="200" placeholder="טקסט או מספר לקוח"></label><label>מתאריך<input type="date" id="from"></label><label>עד תאריך<input type="date" id="to"></label><button type="submit">סינון</button><button type="button" id="refresh">רענון</button></form>
<div id="status" role="status" aria-live="polite"></div><main><aside><h2>שיחות</h2><p class="note">השיחות מבוססות על ההודעות שנטענו</p><div id="conversations"></div><button id="older" hidden>טעינת הודעות ישנות</button></aside><section class="thread"><h2 id="title">בחרו שיחה</h2><div id="messages"></div></section></main><footer>הודעות יוצאות מוצגות רק מתהליכים המחוברים לרישום. כל התאריכים מוצגים לפי שעון ישראל.</footer>
<script nonce="${nonce}">
const $=id=>document.getElementById(id);const rows=new Map();let selected=null,older=null,sync=null,busy=false,filters=new URLSearchParams();const labels=new Map();
const statuses={pending:'הגשה בתהליך',accepted:'ההגשה התקבלה',rejected:'ההגשה נדחתה',unknown:'תוצאת הגשה לא ידועה'};
const fmt=new Intl.DateTimeFormat('he-IL',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Jerusalem'});
function node(tag,content,cls){const e=document.createElement(tag);if(content!==undefined)e.textContent=content;if(cls)e.className=cls;return e;}
function key(m){return JSON.stringify([m.system_number,m.peer_number]);}
async function get(path){const r=await fetch(path,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error(r.status===401?'יש להתחבר מחדש דרך Cloudflare Access':'טעינת הנתונים נכשלה ('+r.status+')');return r.json();}
function render(){const groups=new Map();for(const m of rows.values()){const k=key(m);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(m);}const list=$('conversations');list.replaceChildren();
 const sorted=[...groups.entries()].sort((a,b)=>Math.max(...b[1].map(m=>m.occurred_at))-Math.max(...a[1].map(m=>m.occurred_at)));
 if(!selected||!groups.has(selected))selected=sorted[0]?.[0]||null;
 for(const [k,items] of sorted){const m=items[0];const b=node('button',(labels.get(m.system_number)||m.system_number)+' · '+m.peer_number+' ('+items.length+')');b.type='button';b.setAttribute('aria-pressed',String(selected===k));b.onclick=()=>{selected=k;render();};list.append(b);}
 if(!groups.size)list.append(node('p','אין הודעות עבור הסינון הנוכחי'));const thread=$('messages');thread.replaceChildren();
 const items=groups.get(selected)||[];const first=items[0];$('title').textContent=first?first.peer_number+' · '+(labels.get(first.system_number)||first.system_number):'אין שיחה להצגה';
 for(const m of items.sort((a,b)=>a.occurred_at-b.occurred_at||a.id-b.id)){const b=node('article',undefined,'bubble '+m.direction);b.append(node('div',m.body,'body'));const status=m.direction==='out'?' · '+statuses[m.submission_status]:'';const source=m.time_source==='receipt'?' · זמן קליטה':'';b.append(node('div',(m.direction==='in'?'נכנסת':'יוצאת')+' · '+fmt.format(m.occurred_at)+' · '+m.system_number+status+source,'meta'));thread.append(b);}
 $('older').hidden=!older;}
function params(){const p=new URLSearchParams(filters);p.set('limit','100');return p;}
async function run(task){if(busy)return;busy=true;$('refresh').disabled=true;$('older').disabled=true;$('status').textContent='';try{await task();}catch(e){$('status').textContent=e.message;}finally{busy=false;$('refresh').disabled=false;$('older').disabled=false;}}
async function initial(){const p=params();const d=await get('/api/messages?'+p);rows.clear();for(const m of d.messages)rows.set(m.id,m);older=d.next_cursor;sync=d.sync_cursor;selected=null;render();}
async function refresh(){if(!sync)return initial();for(let i=0;i<20;i++){const p=params();p.set('since',sync);const d=await get('/api/messages?'+p);for(const m of d.messages)rows.set(m.id,m);sync=d.sync_cursor;render();if(!d.has_more)break;}}
$('filters').onsubmit=e=>{e.preventDefault();if(busy)return;run(async()=>{const next=new URLSearchParams();if($('number').value)next.set('system_number',$('number').value);if($('query').value.trim())next.set('q',$('query').value.trim());const start=$('from').value,end=$('to').value;if(start)next.set('from',String(Date.parse(start+'T00:00:00Z')));if(end)next.set('to',String(Date.parse(end+'T00:00:00Z')+86400000));filters=next;await initial();});};
$('refresh').onclick=()=>run(refresh);$('older').onclick=()=>run(async()=>{if(!older)return;const p=params();p.set('cursor',older);const d=await get('/api/messages?'+p);for(const m of d.messages)rows.set(m.id,m);older=d.next_cursor;render();});
setInterval(()=>{if(!document.hidden)run(refresh);},45000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)run(refresh);});
run(async()=>{const d=await get('/api/numbers');for(const n of d.numbers){labels.set(n.number,n.label);const o=node('option',n.label+' · '+n.number);o.value=n.number;$('number').append(o);}await initial();});
</script></body></html>`;}
